// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2IWMMj1ZHojPh5JH_hPvYpY93wbfAAgc',
    appId: '1:908371493185:web:7e46ff924fe2713023e1c0',
    messagingSenderId: '908371493185',
    projectId: 'spotify-app-unique01',
    authDomain: 'spotify-app-unique01.firebaseapp.com',
    storageBucket: 'spotify-app-unique01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCd4aKWniixcFXMPggj_KS8MCUiRayHs',
    appId: '1:908371493185:android:6a9b53b8541b78ad23e1c0',
    messagingSenderId: '908371493185',
    projectId: 'spotify-app-unique01',
    storageBucket: 'spotify-app-unique01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLrkGJXYBoOV1BXKEPs87bx2MO3RXt74',
    appId: '1:908371493185:ios:7f69274e28f6075823e1c0',
    messagingSenderId: '908371493185',
    projectId: 'spotify-app-unique01',
    storageBucket: 'spotify-app-unique01.appspot.com',
    iosBundleId: 'com.example.spotifyAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLrkGJXYBoOV1BXKEPs87bx2MO3RXt74',
    appId: '1:908371493185:ios:7f69274e28f6075823e1c0',
    messagingSenderId: '908371493185',
    projectId: 'spotify-app-unique01',
    storageBucket: 'spotify-app-unique01.appspot.com',
    iosBundleId: 'com.example.spotifyAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2IWMMj1ZHojPh5JH_hPvYpY93wbfAAgc',
    appId: '1:908371493185:web:9feb0ec52dd3f69023e1c0',
    messagingSenderId: '908371493185',
    projectId: 'spotify-app-unique01',
    authDomain: 'spotify-app-unique01.firebaseapp.com',
    storageBucket: 'spotify-app-unique01.appspot.com',
  );
}
